# Generated by Django 4.2.24 on 2025-09-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="home_address",
            field=models.CharField(
                blank=True,
                help_text="Street address used to fetch local weather conditions.",
                max_length=255,
            ),
        ),
    ]
