# Generated by Django 4.2.24 on 2025-10-01 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_systemsettings_home_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-trained_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_data", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="web.trainingprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "captured_at", "id"],
            },
        ),
    ]
